# Usar una imagen base de Ubuntu 12.04
FROM ubuntu:12.04

# Configurar los repositorios antiguos de Ubuntu 12.04
RUN sed -i 's|http://archive.ubuntu.com|http://old-releases.ubuntu.com|g' /etc/apt/sources.list

# Crear un usuario no privilegiado para ejecutar Chromium
RUN groupadd -r chromium && useradd -r -g chromium -m -d /home/chromium chromium

RUN mkdir -p /home/chromium_data

RUN chown chromium:chromium --recursive /home/chromium_data

# Actualizar los repositorios e instalar las dependencias mínimas necesarias para Chromium 38
RUN apt-get update && apt-get install -y \
    wget \
    curl \
    gnupg \
    ca-certificates \
    libx11-6 \
    libxcomposite1 \
    libxdamage1 \
    libxrandr2 \
    libasound2 \
    libnss3 \
    gconf-service \
    libatk1.0-0 \
    libcairo2 \
    libcups2 \
    libgconf-2-4 \
    libgtk2.0-0 \
    libxtst6 \
    xdg-utils \
    chromium-browser \
    chromium-codecs-ffmpeg-extra \
    --no-install-recommends \
    && apt-get clean

# Limpiar el caché de apt para reducir el tamaño de la imagen
RUN rm -rf /var/lib/apt/lists/*

# Configuración para permitir el acceso a la pantalla (X11 forwarding)
ENV DISPLAY=:0
RUN mkdir -p /home/chromium/.X11
VOLUME /tmp/.X11-unix

# Cambiar a un usuario no privilegiado para ejecutar Chromium
USER chromium

# Ejecutar Chromium con acceso a la pantalla
ENTRYPOINT ["chromium-browser", "--no-sandbox", "--disable-gpu", "--remote-debugging-port=9222", "--user-data-dir=/home/chromium_data"]

